### PR TITLE
Create fixtures with sample citizens, bills, and summaries.

### PR DESCRIPTION
**Pull request by jacebrowning**

### CODE REVIEW

**Comment by Crevax** [comment]
When running 'make', I noticed that 'loaddata' doesn't run. I have to do that manually afterwards. What needs to be done to automatically run 'loaddata'?

**Comment by jacebrowning** [comment]
@Crevax when should `loaddata` be run? Whenever a fixture file changes?

**Comment by Crevax** [comment]
It makes sense to me to run it with 'make assets'? Unless you think it's better to only load fixtures manually (which I could understand).

**Comment by jacebrowning** [comment]
@Crevax ok, I think this should work. If the db needs to be created or a fixtures file it modified, `make db` will be run. Is `initial_data.json` still used?

**Comment by Crevax** [comment]
I don't intend on using `initialdata.json` any more.

**Pull request merged**
